scripts:
  main.js: +/main.js
  codemirror.js:
    - node_modules/js-yaml/dist/js-yaml.js
    - node_modules/codemirror/lib/codemirror.js
    - node_modules/codemirror/addon/display/placeholder.js
    - node_modules/codemirror/addon/edit/trailingspace.js
    - node_modules/codemirror/addon/lint/lint.js
    - node_modules/codemirror/addon/lint/yaml-lint.js
    - node_modules/codemirror/addon/search/match-highlighter.js
    - node_modules/codemirror/addon/selection/active-line.js
    - node_modules/codemirror/mode/yaml/yaml.js
    - node_modules/cm-show-invisibles/lib/show-invisibles.js
styles:
  codemirror.css:
    - node_modules/codemirror/lib/codemirror.css
    - node_modules/codemirror/addon/lint/lint.css
dest:
  css: assets/
  js: assets/
  lang: languages/
language:
  domain: pollux
  team: Gemini Labs <support@geminilabs.io>
  translator: Paul Ryley <paul@geminilabs.io>
primary_file: pollux.php
watch:
  js: +/main.js
  php:
    - src/**/*.php
    - views/**/*.php
    - '*.php'
  scss: +/main.scss
